import './style.css';
import './category-menu.css';
import './launcher-enhancements.css';
import { EventsOn, WindowHide, WindowMinimise, WindowToggleMaximise } from '../wailsjs/runtime/runtime';

type Tool = { id:string; name:string; type:string; path:string; icon:string; category:string; description:string; tags:string; weight:number; favorite:boolean; lastRun:number };
type CategoryNode = { name:string; children:string[] };
type RuntimeSettings = { pythonPath:string; java8Path:string; java11Path:string };
const api:any = (window as any).go?.main?.App;
const systemViews=['全部工具','最近启动','我的收藏'];
let all:Tool[] = [], active = '全部工具', query = '', categoryTree:CategoryNode[] = [];
const expandedCategories = new Set<string>(JSON.parse(localStorage.getItem('drgbox.expandedCategories')||'[]'));

document.querySelector('#app')!.innerHTML = `
<main class="shell">
  <aside class="sidebar"><div class="brand"><span class="brand-mark">✦</span><div><b>DRGBOX</b><small>LOCAL TOOLSPACE</small></div></div>
  <div class="side-label">工作区</div><nav id="nav"></nav><div class="side-bottom"><span class="dot"></span> JSON 本地配置<br><em>data/tools.json</em></div></aside>
  <section class="workspace"><header class="topbar"><div class="crumb">工具中心 <span>/</span> 分类工具库</div><div class="top-actions"><button class="settings-btn" id="wallpaper" title="设置">⚙ <span>设置</span></button><button class="profile" id="profile" title="点击更换头像">R</button></div><div class="window-controls" aria-label="窗口控制"><button class="traffic min-dot" id="windowMin" title="最小化"></button><button class="traffic max-dot" id="windowMax" title="最大化 / 还原"></button><button class="traffic close-dot" id="windowClose" title="关闭到后台"></button></div></header>
  <div class="content"><section class="hero"><div class="orb orb-a"></div><div class="orb orb-b"></div><p class="eyebrow">LOCAL · JSON DRIVEN · READY</p><h1>把工具放在该在的位置。</h1><p class="hero-copy">为 SRC 与渗透测试整理的本地工具工作台，搜索、收藏、运行都在一个窗口完成。</p><div class="command"><span>⌕</span><input id="search" placeholder="搜索工具名称、用途、标签或分类…"/><kbd>⌘ K</kbd></div></section>
  <section class="summary"><div><p>工具库</p><strong id="total">—</strong><span> 已收录工具</span></div><div><p>最近启动</p><strong id="recent">—</strong><span> 个工具</span></div><div><p>我的收藏</p><strong id="favCount">—</strong><span> 个常用工具</span></div><button id="reload" class="ghost">↻ 刷新配置</button></section>
  <section class="section-head"><div><h2>全部工具</h2><p id="resultText">正在读取本地配置…</p></div><div class="section-actions"><button id="sync" class="ghost">⌁ 整理工具目录</button><button id="addTool" class="add">＋ 添加工具</button></div></section><div id="chips" class="chips"></div><section id="grid" class="grid"></section></div></section></main><div id="toast" class="toast"></div><div class="wall-panel" id="wallPanel"><div class="panel-title">设置 <button id="closeWall">×</button></div><p class="appearance-label">界面主题</p><div class="theme-picker"><button data-look="light">浅色</button><button data-look="dark">深色</button><button data-look="glass">玻璃</button></div><label class="switch-row"><span>动态流光壁纸<small>低干扰的渐变光影</small></span><input id="motionWall" type="checkbox"><i></i></label><label class="switch-row"><span>亚克力组件<small>半透明、模糊和柔光边框</small></span><input id="acrylicWall" type="checkbox" checked><i></i></label><label class="opacity-row" id="acrylicOpacityRow"><span>亚克力不透明度 <b id="acrylicOpacityValue">58%</b><small>数值越低，背景越通透</small></span><input id="acrylicOpacity" type="range" min="20" max="95" value="58"></label><button class="upload-wall" id="chooseWall">选择图片 / MP4 壁纸</button><button class="reset-wall" id="resetWall">恢复默认壁纸</button></div><video id="wallVideo" class="wall-video" autoplay muted loop playsinline></video>`;

document.body.insertAdjacentHTML('beforeend',`<div id="confirmDialog" class="dialog-backdrop"><section class="dialog-card compact"><h3 id="confirmTitle">确认操作</h3><p id="confirmMessage"></p><div class="dialog-actions"><button class="modal-cancel" data-close-dialog="confirmDialog">取消</button><button id="confirmOk" class="modal-danger">确认</button></div></section></div><div id="categoryDialog" class="dialog-backdrop"><section class="dialog-card compact"><h3 id="categoryDialogTitle">新建分类</h3><p id="categoryDialogCopy">为工具建立一个清晰、易找的分类。</p><label class="form-field">分类名称<input id="categoryName" maxlength="24" placeholder="例如：资产发现工具"></label><div class="dialog-actions"><button class="modal-cancel" data-close-dialog="categoryDialog">取消</button><button id="categorySave" class="modal-primary">创建分类</button></div></section></div><div id="categoryMenu" class="category-menu"><button data-category-action="add-child">＋ 新增二级分类</button><button data-category-action="edit">✎ 编辑分类</button><button class="danger" data-category-action="delete">⌫ 删除分类</button></div><div id="toolDialog" class="dialog-backdrop"><section class="dialog-card tool-editor"><div class="dialog-head"><div><h3 id="toolDialogTitle">添加工具</h3><p>配置工具的启动方式、分类与简介。</p></div><button class="dialog-close" data-close-dialog="toolDialog">×</button></div><div class="tool-form"><label class="form-field">工具名称<input id="toolName" maxlength="80" placeholder="例如：Burp Suite"></label><label class="form-field wide">启动路径<input id="toolPath" placeholder="D:\\Tools\\burp\\burp.exe"></label><label class="form-field wide">自定义图标（可选，留空自动读取系统图标）<div class="field-action"><input id="toolIcon" placeholder="PNG、ICO、JPG 等图片路径"><button type="button" id="chooseToolIcon">选择图标</button></div></label><div class="form-pair"><label class="form-field">工具类型<select id="toolType"><option>GUI应用</option><option>命令行</option><option>批处理</option><option>Python</option><option>JAVA8</option><option>JAVA11</option><option>PowerShell</option><option>目录</option></select></label><label class="form-field">工具分类<select id="toolCategory"></select></label></div><label class="form-field wide">启动参数（可选）<input id="toolArgs" placeholder="例如：-jar app.jar"></label><label class="form-field wide">工具简介<textarea id="toolDescription" maxlength="160" placeholder="简要说明此工具的用途"></textarea></label><label class="form-field wide">标签（可选，逗号分隔）<input id="toolTags" maxlength="60" placeholder="例如：扫描,Web,资产"></label></div><div class="dialog-actions"><button class="modal-cancel" data-close-dialog="toolDialog">取消</button><button id="toolSave" class="modal-primary">保存工具</button></div></section></div>`);
document.body.insertAdjacentHTML('beforeend',`<div id="quickLauncher" class="quick-launcher"><section class="quick-shell"><header><div class="quick-brand"><span>✦</span><b>DRGBOX</b></div><label class="quick-search"><span>⌕</span><input id="quickSearch" autocomplete="off" placeholder="搜索工具、功能或分类…"><kbd>Esc</kbd></label><span id="quickHotkeyHint"></span><button id="quickClose" title="隐藏快捷栏">×</button></header><div class="quick-body"><nav id="quickCategories"></nav><div class="quick-tools"><div class="quick-title-row"><p id="quickTitle"></p><small id="quickCount"></small></div><div id="quickToolList"></div></div></div><footer class="quick-footer"><span>↑↓ 选择工具</span><span>←→ 切换分类</span><span>Enter 启动</span><span>右键 更多操作</span></footer></section></div><div id="toolContextMenu" class="tool-context-menu"><div id="contextToolName"></div><button data-tool-action="run"><span>▶</span>运行工具<kbd>Enter</kbd></button><button data-tool-action="admin"><span>◇</span>管理员运行</button><button data-tool-action="directory"><span>▣</span>打开所在目录</button><button data-tool-action="edit"><span>✎</span>编辑工具</button><button data-tool-action="favorite"><span>☆</span><i id="contextFavoriteLabel">加入收藏</i></button></div>`);
function categoryMatches(toolCategory:string,selected:string){return toolCategory===selected||(!selected.includes('/')&&toolCategory.startsWith(selected+'/'))}
function categoryLabel(path:string){const parts=path.split('/');return parts.length>1?`${parts[0]} · ${parts.slice(1).join(' / ')}`:path}
function topCategories(){return categoryTree.map(node=>node.name)}
let iconRevision=Date.now();
function iconMarkup(tool:Tool){return `<span class="tool-icon ${typeClass(tool.type)}"><span class="icon-fallback">${glyph(tool.type)}</span><img data-tool-icon src="/tool-icon?id=${encodeURIComponent(tool.id)}&v=${iconRevision}" alt=""></span>`}
function bindToolIcons(root:ParentNode=document){root.querySelectorAll<HTMLImageElement>('img[data-tool-icon]').forEach(img=>{img.onload=()=>img.parentElement?.classList.add('has-real-icon');img.onerror=()=>img.remove();if(img.complete&&img.naturalWidth>0)img.parentElement?.classList.add('has-real-icon')})}
type QuickCategory={path:string;label:string;level:number;count:number};
function quickCategories():QuickCategory[]{const entries:QuickCategory[]=[{path:'最近启动',label:'最近使用',level:0,count:all.filter(t=>t.lastRun>0).length},{path:'我的收藏',label:'我的收藏',level:0,count:all.filter(t=>t.favorite).length}];categoryTree.forEach(node=>{entries.push({path:node.name,label:node.name,level:0,count:all.filter(t=>categoryMatches(t.category,node.name)).length});node.children.forEach(child=>{const path=`${node.name}/${child}`;entries.push({path,label:child,level:1,count:all.filter(t=>t.category===path).length})})});return entries}
let quickCategory='',quickQuery='',quickSelected=0,quickVisibleTools:Tool[]=[];
function quickToolsForSelection(){const needle=quickQuery.trim().toLowerCase();let tools=needle?all.filter(t=>`${t.name} ${t.description} ${t.tags} ${t.category} ${t.type}`.toLowerCase().includes(needle)):quickCategory==='最近启动'?all.filter(t=>t.lastRun>0):quickCategory==='我的收藏'?all.filter(t=>t.favorite):all.filter(t=>categoryMatches(t.category,quickCategory));return [...tools].sort((a,b)=>Number(b.favorite)-Number(a.favorite)||b.lastRun-a.lastRun||b.weight-a.weight||a.name.localeCompare(b.name,'zh-CN'))}
function renderQuick(){const categories=quickCategories();if(!quickCategory||!categories.some(c=>c.path===quickCategory))quickCategory=categories[0]?.path||'';document.querySelector('#quickCategories')!.innerHTML=categories.map(c=>`<button class="${c.path===quickCategory?'active':''} ${c.level?'quick-child':''}" data-quick-cat="${escape(c.path)}"><span>${c.level?'↳':'·'} ${escape(c.label)}</span><small>${c.count}</small></button>`).join('');quickVisibleTools=quickToolsForSelection();quickSelected=Math.max(0,Math.min(quickSelected,Math.max(0,quickVisibleTools.length-1)));const title=quickQuery?`搜索：${quickQuery}`:(categories.find(c=>c.path===quickCategory)?.label||quickCategory);document.querySelector('#quickTitle')!.textContent=title;document.querySelector('#quickCount')!.textContent=`${quickVisibleTools.length} 个工具`;document.querySelector('#quickToolList')!.innerHTML=quickVisibleTools.map((t,index)=>`<button class="quick-tool-row ${index===quickSelected?'selected':''}" data-quick-tool="${t.id}" data-tool-id="${t.id}">${iconMarkup(t)}<span class="quick-tool-copy"><b title="${escape(t.name)}">${escape(t.name)}</b><small>${escape(t.description||categoryLabel(t.category))}</small></span><span class="quick-tool-meta"><em>${escape(t.type)}</em>${t.favorite?'<i>★</i>':''}</span></button>`).join('')||'<div class="quick-empty">没有找到匹配工具</div>';document.querySelectorAll<HTMLElement>('[data-quick-cat]').forEach(b=>b.onclick=()=>{quickCategory=b.dataset.quickCat!;quickQuery='';quickSelected=0;document.querySelector<HTMLInputElement>('#quickSearch')!.value='';renderQuick()});document.querySelectorAll<HTMLElement>('[data-quick-tool]').forEach(b=>b.onclick=async()=>{await run(b.dataset.quickTool!);WindowHide()});bindToolIcons(document.querySelector('#quickLauncher')!);setTimeout(()=>document.querySelector('.quick-tool-row.selected')?.scrollIntoView({block:'nearest'}),0)}
function enterQuick(){quickQuery='';quickSelected=0;const input=document.querySelector<HTMLInputElement>('#quickSearch')!;input.value='';renderQuick();document.body.classList.add('quick-open');setTimeout(()=>input.focus(),70)}
function leaveQuick(){document.body.classList.remove('quick-open');closeToolContextMenu()}
document.querySelector<HTMLInputElement>('#quickSearch')!.addEventListener('input',e=>{quickQuery=(e.target as HTMLInputElement).value;quickSelected=0;renderQuick()});document.querySelector('#quickClose')!.addEventListener('click',()=>api.ExitQuickLauncher());EventsOn('drgbox:quick-launcher',enterQuick);EventsOn('drgbox:quick-close',leaveQuick);
document.addEventListener('keydown',async e=>{if(!document.body.classList.contains('quick-open'))return;const categories=quickCategories();if(e.key==='Escape'){e.preventDefault();api.ExitQuickLauncher();return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(quickVisibleTools.length){quickSelected=(quickSelected+(e.key==='ArrowDown'?1:-1)+quickVisibleTools.length)%quickVisibleTools.length;renderQuick()}return}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const current=Math.max(0,categories.findIndex(c=>c.path===quickCategory)),next=(current+(e.key==='ArrowRight'?1:-1)+categories.length)%categories.length;quickCategory=categories[next]?.path||quickCategory;quickQuery='';quickSelected=0;document.querySelector<HTMLInputElement>('#quickSearch')!.value='';renderQuick();return}if(e.key==='Enter'&&quickVisibleTools[quickSelected]){e.preventDefault();await run(quickVisibleTools[quickSelected].id);WindowHide()}});
function filtered(){return all.filter(t=>{const match=active==='全部工具'||(active==='最近启动'&&t.lastRun>0)||(active==='我的收藏'&&t.favorite)||categoryMatches(t.category,active);const hay=`${t.name} ${t.category} ${t.description} ${t.tags} ${t.type}`.toLowerCase();return match&&hay.includes(query.toLowerCase())})}
function toolCard(t:Tool,i:number){return `<article class="tool-card" data-tool-id="${t.id}" style="--d:${Math.min(i,12)*35}ms"><div class="card-top">${iconMarkup(t)}<button class="star" data-fav="${t.id}">${t.favorite?'★':'☆'}</button></div><h3 title="${escape(t.name)}">${escape(t.name)}</h3><p class="desc">${escape(t.description||'已配置本地启动方式')}</p><div class="tags"><span title="${escape(t.category)}">${escape(categoryLabel(t.category))}</span><i>${escape(t.type)}</i></div><div class="card-footer"><small>${t.lastRun?'最近运行':''}</small><div><button class="delete-tool" data-delete="${t.id}">删除</button><button class="run" data-run="${t.id}">运行 <b>→</b></button></div></div></article>`}
function renderToolGroups(items:Tool[]){const grid=document.querySelector<HTMLElement>('#grid')!,parent=categoryTree.find(node=>node.name===active);if(!parent?.children.length){grid.classList.remove('grouped-grid');grid.innerHTML=items.map(toolCard).join('')||'<div class="empty">没有找到匹配工具</div>';return}grid.classList.add('grouped-grid');let cardIndex=0;const groups=parent.children.map((child,index)=>{const path=`${parent.name}/${child}`,tools=items.filter(t=>t.category===path);return `<section class="subcategory-panel" data-category-drop="${escape(path)}" style="--group-index:${index};--group-delay:${Math.min(index,8)*45}ms"><header class="subcategory-panel-head"><div class="subcategory-heading"><span class="subcategory-mark">${String(index+1).padStart(2,'0')}</span><div><small>${escape(parent.name)}</small><h3>${escape(child)}</h3></div></div><div class="subcategory-meta"><span>${tools.length} 个工具</span><button data-cat="${escape(path)}">进入分类 <b>→</b></button></div></header><div class="subcategory-tool-grid">${tools.map(t=>toolCard(t,cardIndex++)).join('')||'<div class="subcategory-empty">该二级分类暂无匹配工具</div>'}</div></section>`}).join('');const direct=items.filter(t=>t.category===parent.name);const directGroup=direct.length?`<section class="subcategory-panel ungrouped-panel" data-category-drop="${escape(parent.name)}" style="--group-index:${parent.children.length};--group-delay:${Math.min(parent.children.length,8)*45}ms"><header class="subcategory-panel-head"><div class="subcategory-heading"><span class="subcategory-mark">··</span><div><small>${escape(parent.name)}</small><h3>未细分</h3></div></div><div class="subcategory-meta"><span>${direct.length} 个工具</span></div></header><div class="subcategory-tool-grid">${direct.map(t=>toolCard(t,cardIndex++)).join('')}</div></section>`:'';grid.innerHTML=groups+directGroup}
function render(){
 const items=filtered(), nav=document.querySelector('#nav')!;
 const systemHtml=systemViews.map(c=>`<button class="nav-item ${c===active?'active':''}" data-cat="${escape(c)}"><span>${c==='全部工具'?'⌘':c==='最近启动'?'◷':'☆'}</span>${escape(c)}</button>`).join('');
 const categoryHtml=categoryTree.map(node=>{const open=expandedCategories.has(node.name)||active.startsWith(node.name+'/'),hasChildren=node.children.length>0,parentActive=active===node.name;const children=node.children.map(child=>{const path=`${node.name}/${child}`;return `<div class="nav-entry child-entry ${active===path?'active':''}" data-category-drop="${escape(path)}"><button class="nav-item child-item ${active===path?'active':''}" data-cat="${escape(path)}" title="${escape(path)}"><span>↳</span>${escape(child)}</button><button class="category-more" data-category-menu="${escape(path)}" title="二级分类操作">•••</button></div>`}).join('');return `<section class="category-group ${open?'expanded':''} ${active.startsWith(node.name+'/')?'contains-active':''}"><div class="nav-entry parent-entry ${parentActive?'active':''}" data-category-drop="${escape(node.name)}"><button class="category-toggle ${hasChildren?'has-children':'empty'}" ${hasChildren?`data-toggle-category="${escape(node.name)}"`:'disabled'} aria-label="${hasChildren?(open?'收起':'展开')+escape(node.name):'暂无二级分类'}" aria-expanded="${open}"><i>›</i></button><button class="nav-item ${parentActive?'active':''}" data-cat="${escape(node.name)}" data-category-level="parent">${escape(node.name)}${hasChildren?`<small>${node.children.length}</small>`:''}</button><button class="category-more" data-category-menu="${escape(node.name)}" title="分类操作">•••</button></div><div class="subcategory-list">${children}</div></section>`}).join('');
 nav.innerHTML=systemHtml+categoryHtml+`<button id="addCategory" class="nav-item add-category-row"><span>＋</span>新建一级分类</button>`;
 const chipCategories=[...systemViews,...topCategories()];document.querySelector('#chips')!.innerHTML=chipCategories.map(c=>`<button class="chip ${c===active?'selected':''}" data-cat="${escape(c)}">${escape(c)}</button>`).join('');
 document.querySelector('#resultText')!.textContent=`${categoryLabel(active)} · ${items.length} 个工具`;
 document.querySelector('#total')!.textContent=String(all.length);document.querySelector('#recent')!.textContent=String(all.filter(t=>t.lastRun>0).length);document.querySelector('#favCount')!.textContent=String(all.filter(t=>t.favorite).length);
 renderToolGroups(items);bindToolIcons(document.querySelector('#grid')!);
 document.querySelectorAll<HTMLElement>('[data-cat]').forEach(e=>e.onclick=()=>{active=e.dataset.cat!;if(active.includes('/'))expandedCategories.add(active.split('/')[0]);render()});document.querySelectorAll<HTMLElement>('[data-toggle-category]').forEach(e=>e.onclick=event=>{event.stopPropagation();const name=e.dataset.toggleCategory!;expandedCategories.has(name)?expandedCategories.delete(name):expandedCategories.add(name);localStorage.setItem('drgbox.expandedCategories',JSON.stringify([...expandedCategories]));render()});document.querySelector('#addCategory')!.addEventListener('click',addCategory);document.querySelectorAll<HTMLElement>('[data-category-menu]').forEach(e=>e.onclick=event=>{event.stopPropagation();openCategoryMenu(e,e.dataset.categoryMenu!)});document.querySelectorAll<HTMLElement>('[data-run]').forEach(e=>e.onclick=()=>run(e.dataset.run!));document.querySelectorAll<HTMLElement>('[data-fav]').forEach(e=>e.onclick=()=>favorite(e.dataset.fav!));document.querySelectorAll<HTMLElement>('[data-delete]').forEach(e=>e.onclick=()=>deleteTool(e.dataset.delete!));
}
function glyph(t:string){if(t==='Python')return 'PY';if(t.startsWith('JAVA'))return 'J';if(t==='GUI应用')return 'APP';if(t==='目录')return 'DIR';if(t==='PowerShell')return 'PS';return 'CLI'}
function typeClass(t:string){return t==='Python'?'python':t.startsWith('JAVA')?'java':t==='GUI应用'?'gui':'cli'}
function escape(s:string){return s.replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]!))}
async function run(id:string){try{const name=await api.RunTool(id);const item=all.find(t=>t.id===id);if(item)item.lastRun=Math.floor(Date.now()/1000);notice(`已启动 ${name}`)}catch(e){notice(`启动失败：${e}`,true)}} async function favorite(id:string){await api.ToggleFavorite(id);await load()}
async function load(){try{all=await api.GetTools();categoryTree=(await api.GetCategoryTree()).map((node:any)=>({name:node.name,children:node.children||[]}));render()}catch(e){notice(`读取本地配置失败：${e}`,true)}}
const modal=(id:string)=>document.querySelector<HTMLElement>('#'+id)!;const closeModal=(id:string)=>modal(id).classList.remove('show');document.querySelectorAll<HTMLElement>('[data-close-dialog]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeDialog!));let pendingConfirm:(()=>void)|null=null;function askConfirm(title:string,message:string,danger=true){document.querySelector('#confirmTitle')!.textContent=title;document.querySelector('#confirmMessage')!.textContent=message;const ok=document.querySelector<HTMLButtonElement>('#confirmOk')!;ok.textContent=danger?'确认删除':'确认';ok.className=danger?'modal-danger':'modal-primary';modal('confirmDialog').classList.add('show');return new Promise<boolean>(resolve=>{pendingConfirm=()=>{closeModal('confirmDialog');resolve(true)};document.querySelectorAll<HTMLElement>('[data-close-dialog="confirmDialog"]').forEach(b=>b.onclick=()=>{closeModal('confirmDialog');resolve(false)});ok.onclick=()=>pendingConfirm?.()})}
type CategoryEditMode='add-parent'|'edit-parent'|'add-child'|'edit-child';
let categoryEditMode:CategoryEditMode='add-parent',editingCategory='',editingParent='',menuCategory='';
const categoryMenu=document.querySelector<HTMLElement>('#categoryMenu')!;
function closeCategoryMenu(){categoryMenu.classList.remove('show')}
function openCategoryMenu(anchor:HTMLElement,name:string){menuCategory=name;const isChild=name.includes('/');categoryMenu.querySelector<HTMLElement>('[data-category-action="add-child"]')!.style.display=isChild?'none':'flex';const r=anchor.getBoundingClientRect();categoryMenu.style.left=`${Math.min(r.right-158,window.innerWidth-170)}px`;categoryMenu.style.top=`${Math.min(r.bottom+6,window.innerHeight-142)}px`;categoryMenu.classList.add('show')}
document.addEventListener('pointerdown',e=>{if(!(e.target as HTMLElement).closest('#categoryMenu,[data-category-menu]'))closeCategoryMenu()});
categoryMenu.querySelectorAll<HTMLElement>('[data-category-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.categoryAction;closeCategoryMenu();if(action==='add-child')openCategoryEditor('',menuCategory);if(action==='edit')editCategory(menuCategory);if(action==='delete')deleteCategory(menuCategory)});
function openCategoryEditor(path='',parent=''){const input=document.querySelector<HTMLInputElement>('#categoryName')!,isChild=path.includes('/'),parts=path.split('/');editingCategory=path;editingParent=parent||(isChild?parts[0]:'');categoryEditMode=path?(isChild?'edit-child':'edit-parent'):(editingParent?'add-child':'add-parent');const childMode=categoryEditMode==='add-child'||categoryEditMode==='edit-child';document.querySelector('#categoryDialogTitle')!.textContent=categoryEditMode==='add-parent'?'新建一级分类':categoryEditMode==='add-child'?'新建二级分类':childMode?'编辑二级分类':'编辑一级分类';document.querySelector('#categoryDialogCopy')!.textContent=childMode?`所属一级分类：${editingParent}`:(path?'修改名称后，包含的二级分类与工具会同步更新。':'创建一级分类后，可从右侧菜单继续添加二级分类。');document.querySelector('#categorySave')!.textContent=path?'保存修改':'创建分类';input.placeholder=childMode?'例如：Spring、ThinkPHP':'例如：框架漏洞利用工具';input.value=isChild?parts.slice(1).join('/'):path;modal('categoryDialog').classList.add('show');setTimeout(()=>{input.focus();input.select()},60)}
async function addCategory(){openCategoryEditor()}
async function editCategory(name=active){if(systemViews.includes(name)){notice('系统视图不能修改',true);return}openCategoryEditor(name)}
document.querySelector('#categorySave')!.addEventListener('click',async()=>{const input=document.querySelector<HTMLInputElement>('#categoryName')!,name=input.value.trim();if(!name){input.focus();return}const oldPath=editingCategory;try{if(categoryEditMode==='edit-parent'){await api.RenameCategory(editingCategory,name);if(expandedCategories.delete(editingCategory))expandedCategories.add(name)}else if(categoryEditMode==='add-child')await api.AddSubcategory(editingParent,name);else if(categoryEditMode==='edit-child')await api.RenameSubcategory(editingParent,editingCategory.split('/').slice(1).join('/'),name);else await api.AddCategory(name);closeModal('categoryDialog');if(categoryEditMode==='add-child'||categoryEditMode==='edit-child')expandedCategories.add(editingParent);await load();if(categoryEditMode==='edit-parent')active=name;else if(categoryEditMode==='add-child'||categoryEditMode==='edit-child')active=`${editingParent}/${name}`;else active=name;localStorage.setItem('drgbox.expandedCategories',JSON.stringify([...expandedCategories]));render();notice(oldPath?'分类修改已保存':`已创建${editingParent?'二级':'一级'}分类：${name}`)}catch(e){notice(`保存分类失败：${e}`,true)}});
async function deleteCategory(path=active){if(systemViews.includes(path)){notice('系统视图不能删除',true);return}const isChild=path.includes('/'),[parent,...childParts]=path.split('/'),child=childParts.join('/');const message=isChild?`删除二级分类「${child}」？其中工具将移至「${parent}」。`:`删除一级分类「${path}」及其全部二级分类？其中工具将自动移至其他分类。`;if(!await askConfirm(isChild?'删除二级分类':'删除一级分类',message))return;try{if(isChild)await api.DeleteSubcategory(parent,child);else{await api.DeleteCategory(path);expandedCategories.delete(path)}if(active===path||(!isChild&&active.startsWith(path+'/')))active=isChild?parent:'全部工具';localStorage.setItem('drgbox.expandedCategories',JSON.stringify([...expandedCategories]));await load();notice('分类已删除')}catch(e){notice(`删除分类失败：${e}`,true)}}
let editingTool:Tool|null=null;const field=(id:string)=>document.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('#'+id)!;function openToolEditor(tool?:Tool){editingTool=tool||null;document.querySelector('#toolDialogTitle')!.textContent=tool?'编辑工具':'添加工具';document.querySelector('#toolSave')!.textContent=tool?'保存修改':'添加工具';const select=field('toolCategory') as HTMLSelectElement;select.innerHTML=categoryTree.map(node=>`<optgroup label="${escape(node.name)}"><option value="${escape(node.name)}">${escape(node.name)}（未细分）</option>${node.children.map(child=>`<option value="${escape(node.name+'/'+child)}">↳ ${escape(child)}</option>`).join('')}</optgroup>`).join('');field('toolName').value=tool?.name||'';field('toolPath').value=tool?.path||'';field('toolIcon').value=tool?.icon||'';field('toolType').value=tool?.type||'GUI应用';const fallback=categoryTree.find(n=>n.name==='其他工具')?.name||categoryTree[0]?.name||'';field('toolCategory').value=tool?.category||(systemViews.includes(active)?fallback:active);field('toolArgs').value=(tool as any)?.args||'';field('toolDescription').value=tool?.description||'';field('toolTags').value=tool?.tags||'';modal('toolDialog').classList.add('show');setTimeout(()=>field('toolName').focus(),60)}async function addTool(){openToolEditor()}async function saveTool(){const name=field('toolName').value.trim(),path=field('toolPath').value.trim();if(!name||!path){notice('请填写工具名称和启动路径',true);return}const t:any={id:editingTool?.id||'',name,path,icon:field('toolIcon').value.trim(),type:field('toolType').value,category:field('toolCategory').value,description:field('toolDescription').value.trim(),tags:field('toolTags').value.trim(),args:field('toolArgs').value.trim(),weight:editingTool?.weight||0,favorite:editingTool?.favorite||false,lastRun:editingTool?.lastRun||0};try{if(editingTool)await api.UpdateTool(t);else await api.AddTool(t);closeModal('toolDialog');iconRevision=Date.now();await load();notice(editingTool?'工具已更新':'工具已添加')}catch(e){notice(`${editingTool?'保存':'添加'}失败：${e}`,true)}}document.querySelector('#toolSave')!.addEventListener('click',saveTool);document.querySelector('#chooseToolIcon')!.addEventListener('click',async()=>{try{const path=await api.ChooseToolIcon();if(path)field('toolIcon').value=path}catch(e){notice(`选择图标失败：${e}`,true)}});
async function deleteTool(id:string){const tool=all.find(t=>t.id===id);if(!await askConfirm('从工具箱移除',`移除「${tool?.name||'该工具'}」？不会删除磁盘文件。`))return;try{await api.DeleteTool(id);await load();notice('已从工具箱移除')}catch(e){notice(`删除失败：${e}`,true)}}
async function syncTools(){try{const r=await api.SyncToolDirectory();await load();notice(`整理完成：新增 ${r.added} 个，当前共 ${r.total} 个工具`)}catch(e){notice(`整理失败：${e}`,true)}}
const toolContextMenu=document.querySelector<HTMLElement>('#toolContextMenu')!;let contextToolId='';
function closeToolContextMenu(){toolContextMenu.classList.remove('show');contextToolId=''}
function openToolContextMenu(event:MouseEvent,id:string){const tool=all.find(t=>t.id===id);if(!tool)return;event.preventDefault();contextToolId=id;document.querySelector('#contextToolName')!.textContent=tool.name;document.querySelector('#contextFavoriteLabel')!.textContent=tool.favorite?'取消收藏':'加入收藏';toolContextMenu.style.left=`${Math.min(event.clientX,window.innerWidth-232)}px`;toolContextMenu.style.top=`${Math.min(event.clientY,window.innerHeight-248)}px`;toolContextMenu.classList.add('show')}
document.addEventListener('contextmenu',event=>{const target=(event.target as HTMLElement).closest<HTMLElement>('[data-tool-id]');if(target)openToolContextMenu(event,target.dataset.toolId!);else closeToolContextMenu()});document.addEventListener('pointerdown',event=>{if(!(event.target as HTMLElement).closest('#toolContextMenu'))closeToolContextMenu()});document.addEventListener('scroll',closeToolContextMenu,true);
toolContextMenu.querySelectorAll<HTMLElement>('[data-tool-action]').forEach(button=>button.onclick=async()=>{const id=contextToolId,action=button.dataset.toolAction,tool=all.find(t=>t.id===id);if(!tool)return;closeToolContextMenu();try{if(action==='run'){await run(id);if(document.body.classList.contains('quick-open'))WindowHide()}else if(action==='admin'){const name=await api.RunToolAsAdmin(id);tool.lastRun=Math.floor(Date.now()/1000);notice(`已用管理员权限启动 ${name}`);if(document.body.classList.contains('quick-open'))WindowHide()}else if(action==='directory'){await api.OpenToolDirectory(id);notice('已打开工具所在目录')}else if(action==='edit'){if(document.body.classList.contains('quick-open')){await api.ExitQuickLauncher();setTimeout(()=>openToolEditor(tool),100)}else openToolEditor(tool)}else if(action==='favorite'){await api.ToggleFavorite(id);await load();if(document.body.classList.contains('quick-open'))renderQuick();notice(tool.favorite?'已取消收藏':'已加入收藏')}}catch(e){notice(`操作失败：${e}`,true)}});
function injectEditButtons(){document.querySelectorAll<HTMLElement>('.delete-tool').forEach(del=>{const id=del.dataset.delete;if(id&&!del.parentElement?.querySelector('[data-edit]'))del.insertAdjacentHTML('beforebegin',`<button class="edit-tool" data-edit="${id}">编辑</button>`)})}new MutationObserver(injectEditButtons).observe(document.querySelector('#grid')!,{childList:true,subtree:true});document.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLElement>('[data-edit]');if(button){const tool=all.find(t=>t.id===button.dataset.edit);if(tool)openToolEditor(tool)}});
let draggingCategory='',draggingTool='';
function enableDrag(){document.querySelectorAll<HTMLElement>('#nav [data-category-level="parent"]').forEach(item=>item.draggable=true);document.querySelectorAll<HTMLElement>('.tool-card').forEach(card=>card.draggable=true)}
function clearDropTargets(){document.querySelectorAll('.category-drop-target,.tool-order-drop-target').forEach(x=>x.classList.remove('category-drop-target','tool-order-drop-target'))}
new MutationObserver(enableDrag).observe(document.querySelector('#app')!,{childList:true,subtree:true});
document.addEventListener('dragstart',e=>{const el=e.target as HTMLElement;const cat=el.closest<HTMLElement>('#nav [data-category-level="parent"]');const card=el.closest<HTMLElement>('.tool-card');if(cat){draggingCategory=cat.dataset.cat||'';cat.classList.add('dragging');e.dataTransfer?.setData('text/plain',`category:${draggingCategory}`)}else if(card&&!el.closest('button')){draggingTool=card.querySelector<HTMLElement>('[data-delete]')?.dataset.delete||'';card.classList.add('dragging');e.dataTransfer?.setData('text/plain',`tool:${draggingTool}`);if(e.dataTransfer)e.dataTransfer.effectAllowed='move'}});
document.addEventListener('dragover',e=>{const el=e.target as HTMLElement,card=el.closest<HTMLElement>('.tool-card'),categoryTarget=!card?el.closest<HTMLElement>('[data-category-drop]'):null,categoryOrderTarget=el.closest<HTMLElement>('#nav [data-category-level="parent"]');clearDropTargets();if(draggingTool&&categoryTarget){e.preventDefault();categoryTarget.classList.add('category-drop-target');if(e.dataTransfer)e.dataTransfer.dropEffect='move'}else if(draggingTool&&card){e.preventDefault();if(!card.classList.contains('dragging'))card.classList.add('tool-order-drop-target')}else if(draggingCategory&&categoryOrderTarget){e.preventDefault();if(!categoryOrderTarget.classList.contains('dragging'))categoryOrderTarget.classList.add('tool-order-drop-target')}});
document.addEventListener('drop',async e=>{e.preventDefault();const el=e.target as HTMLElement,card=el.closest<HTMLElement>('.tool-card'),categoryTarget=!card?el.closest<HTMLElement>('[data-category-drop]'):null,categoryOrderTarget=el.closest<HTMLElement>('#nav [data-category-level="parent"]');try{if(categoryTarget&&draggingTool){const target=categoryTarget.dataset.categoryDrop!,tool=all.find(t=>t.id===draggingTool);if(tool?.category===target)notice(`「${tool.name}」已经在该分类中`);else{await api.MoveToolToCategory(draggingTool,target);await load();notice(`已移动到「${categoryLabel(target)}」`)}}else if(categoryOrderTarget&&draggingCategory){await api.MoveCategory(draggingCategory,categoryOrderTarget.dataset.cat);await load();notice('一级分类顺序已更新')}else if(card&&draggingTool){const target=card.querySelector<HTMLElement>('[data-delete]')?.dataset.delete;if(target&&target!==draggingTool){await api.MoveTool(draggingTool,target);await load();notice('工具顺序已更新')}}}catch(err){notice(`拖动失败：${err}`,true)}finally{draggingCategory='';draggingTool='';clearDropTargets();document.querySelectorAll('.dragging').forEach(x=>x.classList.remove('dragging'))}});
document.addEventListener('dragend',()=>{draggingCategory='';draggingTool='';clearDropTargets();document.querySelectorAll('.dragging').forEach(x=>x.classList.remove('dragging'))});
function notice(s:string,bad=false){const e=document.querySelector('#toast')!;e.textContent=s;e.className=`toast show ${bad?'bad':''}`;setTimeout(()=>e.className='toast',2600)}
function setLook(look:string){document.body.classList.remove('dark','liquid-glass','solid-light');if(look==='dark')document.body.classList.add('dark');else if(look==='glass')document.body.classList.add('liquid-glass');else document.body.classList.add('solid-light');localStorage.setItem('drgbox.look',look);document.querySelectorAll<HTMLElement>('[data-look]').forEach(b=>b.classList.toggle('selected',b.dataset.look===look))}
document.querySelector<HTMLInputElement>('#search')!.oninput=e=>{query=(e.target as HTMLInputElement).value;render()};document.querySelector('#reload')!.addEventListener('click',load);document.querySelector('#addTool')!.addEventListener('click',addTool);document.querySelector('#sync')!.addEventListener('click',syncTools);document.querySelectorAll<HTMLElement>('[data-look]').forEach(b=>b.addEventListener('click',()=>setLook(b.dataset.look||'light')));setLook(localStorage.getItem('drgbox.look')||'light');
document.querySelector('#windowClose')!.addEventListener('click',WindowHide);document.querySelector('#windowMin')!.addEventListener('click',WindowMinimise);document.querySelector('#windowMax')!.addEventListener('click',WindowToggleMaximise);
const wallPanel=document.querySelector<HTMLElement>('#wallPanel')!, motion=document.querySelector<HTMLInputElement>('#motionWall')!, acrylic=document.querySelector<HTMLInputElement>('#acrylicWall')!, acrylicOpacity=document.querySelector<HTMLInputElement>('#acrylicOpacity')!, acrylicOpacityValue=document.querySelector<HTMLElement>('#acrylicOpacityValue')!;
wallPanel.insertAdjacentHTML('beforeend',`<div class="quick-setting"><span>快捷分类栏<small>按下全局快捷键快速启动分类工具</small></span><select id="quickHotkey"><option>Ctrl+Shift+Space</option><option>Ctrl+Alt+Space</option><option>Ctrl+Shift+Q</option><option>Ctrl+Alt+Q</option></select></div><section class="runtime-settings"><div class="runtime-heading"><span>运行环境<small>为空时使用 DRGBOX 内置环境，其次使用系统 PATH</small></span><button id="runtimeReset" type="button">恢复内置</button></div><label class="runtime-row"><b>Python</b><div class="runtime-path"><input id="pythonRuntime" spellcheck="false" placeholder="python.exe 或 Python 安装目录"><button type="button" data-runtime-browse="python">浏览</button></div></label><label class="runtime-row"><b>Java 8</b><div class="runtime-path"><input id="java8Runtime" spellcheck="false" placeholder="javaw.exe、JRE/JDK 或 bin 目录"><button type="button" data-runtime-browse="java8">浏览</button></div></label><label class="runtime-row"><b>Java 11</b><div class="runtime-path"><input id="java11Runtime" spellcheck="false" placeholder="javaw.exe、JRE/JDK 或 bin 目录"><button type="button" data-runtime-browse="java11">浏览</button></div></label><button class="runtime-save" id="runtimeSave" type="button">保存运行环境</button></section>`);
const quickHotkey=document.querySelector<HTMLSelectElement>('#quickHotkey')!;api.GetQuickHotkey().then((v:string)=>{if(Array.from(quickHotkey.options).some(o=>o.value===v))quickHotkey.value=v;document.querySelector('#quickHotkeyHint')!.textContent=v});quickHotkey.addEventListener('change',async()=>{try{await api.SetQuickHotkey(quickHotkey.value);document.querySelector('#quickHotkeyHint')!.textContent=quickHotkey.value;notice(`快捷键已设为 ${quickHotkey.value}`)}catch(e){notice(`快捷键设置失败：${e}`,true)}});
const runtimeInputs:Record<string,HTMLInputElement>={python:document.querySelector('#pythonRuntime')!,java8:document.querySelector('#java8Runtime')!,java11:document.querySelector('#java11Runtime')!};
async function loadRuntimeSettings(){try{const value:RuntimeSettings=await api.GetRuntimeSettings();runtimeInputs.python.value=value.pythonPath||'';runtimeInputs.java8.value=value.java8Path||'';runtimeInputs.java11.value=value.java11Path||''}catch(e){notice(`读取运行环境失败：${e}`,true)}}
document.querySelectorAll<HTMLButtonElement>('[data-runtime-browse]').forEach(button=>button.addEventListener('click',async()=>{const kind=button.dataset.runtimeBrowse!;try{const path=await api.ChooseRuntimeExecutable(kind);if(path)runtimeInputs[kind].value=path}catch(e){notice(`选择运行环境失败：${e}`,true)}}));
document.querySelector('#runtimeSave')!.addEventListener('click',async()=>{const button=document.querySelector<HTMLButtonElement>('#runtimeSave')!;button.disabled=true;button.textContent='正在校验…';try{await api.SaveRuntimeSettings({pythonPath:runtimeInputs.python.value.trim(),java8Path:runtimeInputs.java8.value.trim(),java11Path:runtimeInputs.java11.value.trim()});await loadRuntimeSettings();notice('Python、Java 8、Java 11 运行环境已保存')}catch(e){notice(`保存运行环境失败：${e}`,true)}finally{button.disabled=false;button.textContent='保存运行环境'}});
document.querySelector('#runtimeReset')!.addEventListener('click',async()=>{try{await api.SaveRuntimeSettings({pythonPath:'',java8Path:'',java11Path:''});await loadRuntimeSettings();notice('已恢复使用内置运行环境')}catch(e){notice(`恢复运行环境失败：${e}`,true)}});loadRuntimeSettings();
const video=document.querySelector<HTMLVideoElement>('#wallVideo')!;
function setWall(data?:string|null){const isVideo=!!data&&/\.(mp4|webm|mov|mkv)(\?|$)/i.test(data);video.src='';video.classList.toggle('show',isVideo);if(isVideo&&data){video.src=data;video.play().catch(()=>{});document.body.style.removeProperty('--wallpaper');document.body.classList.add('custom-wallpaper','video-wallpaper')}else if(data){document.body.style.setProperty('--wallpaper',`url("${data}")`);document.body.classList.add('custom-wallpaper');document.body.classList.remove('video-wallpaper')}else{document.body.style.removeProperty('--wallpaper');document.body.classList.remove('custom-wallpaper','video-wallpaper')}}
function applyAcrylicOpacity(value:string){const amount=Math.max(20,Math.min(95,Number(value)||58));acrylicOpacity.value=String(amount);acrylicOpacityValue.textContent=`${amount}%`;document.body.style.setProperty('--acrylic-alpha',String(amount/100));localStorage.setItem('drgbox.acrylicOpacity',String(amount))}
async function restoreAppearance(){setWall(await api.GetWallpaper());motion.checked=localStorage.getItem('drgbox.motion')==='true';acrylic.checked=localStorage.getItem('drgbox.acrylic')!=='false';applyAcrylicOpacity(localStorage.getItem('drgbox.acrylicOpacity')||'58');document.body.classList.toggle('motion-wallpaper',motion.checked);document.body.classList.toggle('no-acrylic',!acrylic.checked)}
const profile=document.querySelector<HTMLButtonElement>('#profile')!;function setAvatar(url?:string){if(url){profile.innerHTML=`<img src="${url}${url.includes('?')?'&':'?'}v=${Date.now()}" alt="头像">`;profile.classList.add('has-avatar')}else{profile.textContent='R';profile.classList.remove('has-avatar')}}async function restoreAvatar(){setAvatar(await api.GetAvatar())}profile.addEventListener('click',async()=>{try{const url=await api.ChooseAvatar();if(url){setAvatar(url);notice('头像已更新')}}catch(e){notice(`头像导入失败：${e}`,true)}});
const settingsButton=document.querySelector<HTMLButtonElement>('#wallpaper')!;settingsButton.onclick=()=>wallPanel.classList.toggle('show');document.querySelector('#closeWall')!.addEventListener('click',()=>wallPanel.classList.remove('show'));motion.addEventListener('change',()=>{localStorage.setItem('drgbox.motion',String(motion.checked));document.body.classList.toggle('motion-wallpaper',motion.checked)});acrylic.addEventListener('change',()=>{localStorage.setItem('drgbox.acrylic',String(acrylic.checked));document.body.classList.toggle('no-acrylic',!acrylic.checked)});acrylicOpacity.addEventListener('input',()=>applyAcrylicOpacity(acrylicOpacity.value));document.querySelector('#chooseWall')!.addEventListener('click',async()=>{try{const url=await api.ChooseWallpaper();if(url){setWall(url);notice('壁纸已导入')}}catch(e){notice(`导入壁纸失败：${e}`,true)}});document.querySelector('#resetWall')!.addEventListener('click',async()=>{await api.ClearWallpaper();setWall(null);notice('已恢复默认壁纸')});restoreAppearance();restoreAvatar();
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('#search')!.focus()}});load();
