// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddSubcategory(arg1, arg2) {
  return window['go']['main']['App']['AddSubcategory'](arg1, arg2);
}

export function AddTool(arg1) {
  return window['go']['main']['App']['AddTool'](arg1);
}

export function ChooseAvatar() {
  return window['go']['main']['App']['ChooseAvatar']();
}

export function ChooseRuntimeExecutable(arg1) {
  return window['go']['main']['App']['ChooseRuntimeExecutable'](arg1);
}

export function ChooseToolIcon() {
  return window['go']['main']['App']['ChooseToolIcon']();
}

export function ChooseWallpaper() {
  return window['go']['main']['App']['ChooseWallpaper']();
}

export function CleanInvalidTools() {
  return window['go']['main']['App']['CleanInvalidTools']();
}

export function ClearWallpaper() {
  return window['go']['main']['App']['ClearWallpaper']();
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSubcategory(arg1, arg2) {
  return window['go']['main']['App']['DeleteSubcategory'](arg1, arg2);
}

export function DeleteTool(arg1) {
  return window['go']['main']['App']['DeleteTool'](arg1);
}

export function ExitQuickLauncher() {
  return window['go']['main']['App']['ExitQuickLauncher']();
}

export function GetAvatar() {
  return window['go']['main']['App']['GetAvatar']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryTree() {
  return window['go']['main']['App']['GetCategoryTree']();
}

export function GetQuickHotkey() {
  return window['go']['main']['App']['GetQuickHotkey']();
}

export function GetRuntimeSettings() {
  return window['go']['main']['App']['GetRuntimeSettings']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetWallpaper() {
  return window['go']['main']['App']['GetWallpaper']();
}

export function MoveCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveCategory'](arg1, arg2);
}

export function MoveTool(arg1, arg2) {
  return window['go']['main']['App']['MoveTool'](arg1, arg2);
}

export function MoveToolToCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveToolToCategory'](arg1, arg2);
}

export function OpenToolDirectory(arg1) {
  return window['go']['main']['App']['OpenToolDirectory'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RenameSubcategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSubcategory'](arg1, arg2, arg3);
}

export function RunTool(arg1) {
  return window['go']['main']['App']['RunTool'](arg1);
}

export function RunToolAsAdmin(arg1) {
  return window['go']['main']['App']['RunToolAsAdmin'](arg1);
}

export function SaveRuntimeSettings(arg1) {
  return window['go']['main']['App']['SaveRuntimeSettings'](arg1);
}

export function ServeAvatar(arg1, arg2) {
  return window['go']['main']['App']['ServeAvatar'](arg1, arg2);
}

export function ServeToolIcon(arg1, arg2) {
  return window['go']['main']['App']['ServeToolIcon'](arg1, arg2);
}

export function ServeWallpaper(arg1, arg2) {
  return window['go']['main']['App']['ServeWallpaper'](arg1, arg2);
}

export function SetQuickHotkey(arg1) {
  return window['go']['main']['App']['SetQuickHotkey'](arg1);
}

export function SyncToolDirectory() {
  return window['go']['main']['App']['SyncToolDirectory']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
