// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddSubcategory(arg1:string,arg2:string):Promise<void>;

export function AddTool(arg1:main.Tool):Promise<void>;

export function ChooseAvatar():Promise<string>;

export function ChooseRuntimeExecutable(arg1:string):Promise<string>;

export function ChooseToolIcon():Promise<string>;

export function ChooseWallpaper():Promise<string>;

export function CleanInvalidTools():Promise<number>;

export function ClearWallpaper():Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteSubcategory(arg1:string,arg2:string):Promise<void>;

export function DeleteTool(arg1:string):Promise<void>;

export function ExitQuickLauncher():Promise<void>;

export function GetAvatar():Promise<string>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryTree():Promise<Array<main.CategoryNode>>;

export function GetQuickHotkey():Promise<string>;

export function GetRuntimeSettings():Promise<main.RuntimeSettings>;

export function GetTools():Promise<Array<main.Tool>>;

export function GetWallpaper():Promise<string>;

export function MoveCategory(arg1:string,arg2:string):Promise<void>;

export function MoveTool(arg1:string,arg2:string):Promise<void>;

export function MoveToolToCategory(arg1:string,arg2:string):Promise<void>;

export function OpenToolDirectory(arg1:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function RenameSubcategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunTool(arg1:string):Promise<string>;

export function RunToolAsAdmin(arg1:string):Promise<string>;

export function SaveRuntimeSettings(arg1:main.RuntimeSettings):Promise<void>;

export function ServeAvatar(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function ServeToolIcon(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function ServeWallpaper(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetQuickHotkey(arg1:string):Promise<void>;

export function SyncToolDirectory():Promise<main.SyncSummary>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function UpdateTool(arg1:main.Tool):Promise<void>;
